#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@ironcode-ai/script"
const modelsUrl = process.env.IRONCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    minify: true, // Enable minification for smaller binary size
    // Bytecode disabled: @opentui/core uses top-level await which is incompatible with Bun's bytecode mode.
    // Trade-off: ~100-200ms slower startup, but runtime performance is unaffected.
    // Can be re-enabled when @opentui/core removes top-level await or Bun fixes the limitation.
    bytecode: false,
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/ironcode`,
      execArgv: [`--user-agent=ironcode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      IRONCODE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      IRONCODE_WORKER_PATH: workerPath,
      IRONCODE_CHANNEL: `'${Script.channel}'`,
      IRONCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`

  // Copy Rust native library to dist (must be built beforehand for target platform)
  const libExt = item.os === "win32" ? "dll" : item.os === "darwin" ? "dylib" : "so"

  // Rust cdylib naming convention:
  // Windows: ironcode_tool.dll (primary output)
  // Unix: libironcode_tool.{so|dylib}
  const primaryLibName = item.os === "win32" ? `ironcode_tool.${libExt}` : `libironcode_tool.${libExt}`
  const nativeLibPath = path.join(dir, `native/tool/target/release/${primaryLibName}`)

  if (fs.existsSync(nativeLibPath)) {
    // For Windows, copy the DLL with both names (with and without 'lib' prefix)
    // to support different runtime lookup conventions
    if (item.os === "win32") {
      // Copy as ironcode_tool.dll
      const destPath1 = path.join(dir, `dist/${name}/bin/ironcode_tool.dll`)
      await Bun.write(destPath1, Bun.file(nativeLibPath))
      console.log(`Copied ironcode_tool.dll to ${name}/bin`)

      // Also copy as libironcode_tool.dll
      const destPath2 = path.join(dir, `dist/${name}/bin/libironcode_tool.dll`)
      await Bun.write(destPath2, Bun.file(nativeLibPath))
      console.log(`Copied libironcode_tool.dll to ${name}/bin`)
    } else {
      // Unix: just copy as-is
      const destPath = path.join(dir, `dist/${name}/bin/${primaryLibName}`)
      await Bun.write(destPath, Bun.file(nativeLibPath))
      console.log(`Copied ${primaryLibName} to ${name}/bin`)
    }
  } else {
    console.warn(`Warning: Native library not found at ${nativeLibPath}`)
    console.warn(`You may need to build the Rust library for ${item.os}-${item.arch} first`)
  }

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  const archives: string[] = []

  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      const archivePath = `../../${key}.tar.gz`
      await $`tar -czf ${archivePath} *`.cwd(`dist/${key}/bin`)
      archives.push(`./dist/${key}.tar.gz`)
    } else {
      const archivePath = `../../${key}.zip`
      const binDir = path.resolve(`dist/${key}/bin`)
      const zipPath = path.resolve(`dist/${key}.zip`)

      if (process.platform === "win32") {
        // Use PowerShell on Windows
        await $`powershell -Command "Compress-Archive -Path '${binDir}/*' -DestinationPath '${zipPath}' -Force"`
      } else {
        // Use zip on macOS/Linux
        await $`zip -r ${archivePath} *`.cwd(`dist/${key}/bin`)
      }
      archives.push(`./dist/${key}.zip`)
    }
  }

  // Only upload archives that were actually created
  if (archives.length > 0) {
    await $`gh release upload v${Script.version} ${archives} --clobber`
  }
}

export { binaries }
