#!/usr/bin/env bun
// Build-time codegen: reads .ironcode/skill/SKILL.md files and generates
// src/skill/builtin-skills-snapshot.ts with embedded content.
//
// Usage: bun run script/gen-builtin-skills.ts
// Called automatically by build.ts before compilation.

import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pkgRoot = path.resolve(__dirname, "..") // packages/ironcode
const skillsDir = path.join(pkgRoot, "skills")
const outFile = path.join(pkgRoot, "src/skill/builtin-skills-snapshot.ts")

interface SkillEntry {
  /** Directory name (e.g. "ceo-review") */
  name: string
  /** Full raw content of SKILL.md */
  content: string
}

const skills: SkillEntry[] = []

const glob = new Bun.Glob("*/SKILL.md")
for await (const match of glob.scan({ cwd: skillsDir, absolute: false })) {
  const dirName = path.dirname(match)
  const fullPath = path.join(skillsDir, match)
  const content = await Bun.file(fullPath).text()
  skills.push({ name: dirName, content })
}

// Sort for deterministic output
skills.sort((a, b) => a.name.localeCompare(b.name))

// Generate TypeScript source
const lines = [
  "// Auto-generated by script/gen-builtin-skills.ts — do not edit",
  `// Generated at: ${new Date().toISOString()}`,
  "",
  "export interface BuiltinSkill {",
  "  name: string",
  "  content: string",
  "}",
  "",
  "export const builtinSkills: BuiltinSkill[] = [",
]

for (const skill of skills) {
  // Use JSON.stringify to safely escape the content as a string literal
  lines.push(`  {`)
  lines.push(`    name: ${JSON.stringify(skill.name)},`)
  lines.push(`    content: ${JSON.stringify(skill.content)},`)
  lines.push(`  },`)
}

lines.push("]")
lines.push("")

await Bun.write(outFile, lines.join("\n"))
console.log(`Generated builtin-skills-snapshot.ts with ${skills.length} skill(s): ${skills.map((s) => s.name).join(", ")}`)
